### ISSUE TITLE
READ ME

### ISSUE THREAD

**Issue by Josy-git** [Timon-Ludwigs/Gruppenarbeit-Wissenschtliches-Arbeiten#10]
Hey,

habt ihr noch eine Idee was in unser README gehört?

Vielleicht die Aufgabenstellung?

**Comment by MelissaWald** [comment]
Ja, also die Aufgabenstellung find ich schonmal gut.

**Comment by Josy-git** [comment]
Hat noch jemand eine Idee, was ins README soll?
Oder reicht das wie wir es bisher haben?

**Comment by Timon-Ludwigs** [comment]
Wollen wir unsere Nachnamen auch in das Readme mit aufnehmen?

**Comment by NSCI16** [comment]
@Timon-Ludwigs  können wir machen.
Wir haben unsere Namen und einen groben Verlauf unserer Arbeit angegeben. Das sollte reichen.

**Comment by Josy-git** [comment]
alles klar. so machen wir das!

**Comment by Timon-Ludwigs** [comment]
Ok, dann haben wir das README auch fertig und können dieses Issue schließen.
