### ISSUE TITLE
Diskussion Ergebnisse

### ISSUE THREAD

**Issue by MelissaWald** [Timon-Ludwigs/Gruppenarbeit-Wissenschtliches-Arbeiten#12]
**Hier können wir alle zusammen über die Ergebnisse der Analyse diskutieren.**

Also es ging ja anscheinend um Studierende im Datensatz. Beim Alter konnte wir erkennen, dass die meisten Studierenden Mitte 20 sind. Ich denke, das war ja auch ziemlich offensichtlich. Außerdem studieren ja die meisten Statistik oder Data Science.

Was ich sehr interessant fand war, dass man einen Zusammenhang zwischen dem Interesse an Informatik und dem Interessa an Mathe erkennen kann.

**Comment by Josy-git** [comment]
Melissa, was für einen Zusammenhang hast du denn erkennen können? Also was schätzt du, haben wir simuliert? Erkennst du etwas?

**Comment by Josy-git** [comment]
ich muss auf jeden Fall schon mal sagen, dass ihr drei das sehr ausführlich ausgewertet habt. Sehr cool! Schöne Grafiken! Ich bin gespannt, ob ihr unseren gedachten Zusammenhang herausbekommen habt, also ob dazu die Daten "gut" genug simuliert wurden ;-)

**Comment by MelissaWald** [comment]
Also ich erkenne, dass die Studierenden die ein hohes Interesse an Mathe haben auch ein hohes Interesse an Informatik. Sehen die anderen das auch so?

**Comment by joshuathejas** [comment]
Ja sehe ich auch so! Es sieht so aus, dass es einen klaren Zusammenhang zwischen Interesse an Mathematik und Interesse an Informatik gibt.

**Comment by joshuathejas** [comment]
Ich muss jedoch erwähnen, die Grafiken über MatheLK und Alter erscheinen mir nicht von gorßem Nutzen. Natürlich ist es gut zu visualisieren, um zu sehen wie viele Studierenden unter welchem Alter es genommen haben, aber das ganze zu  interpretieren und einen Zusammenhang zu sehen finde cih schwierig! Ich weiß nicht wie ihr das sieht.

**Comment by Timon-Ludwigs** [comment]
Zunächst einmal muss ich euch für eure schöne Auswertung loben. Das ist richtig gut geworden. Und ich stimme @joshuathejas in dem Punkt der Visualisierung, bei MatheLK und Alter zu. Als ich die Funktion in der Aufgabe zuvor geschrieben habe, erschien mir das nicht besonders sinnvoll.

**Comment by MelissaWald** [comment]
Das mit der Visualisierung sehe ich auch so. Das hat uns nicht wirklich was gebracht.

**Comment by NSCI16** [comment]
@joshuathejas  dem stimme ich auch zu. Es ist aber zu entnehmen, dass der/die jüngste Studierende etwa 19 Jahre ist und der/die Älteste 31 Jahre alt ist. Wie @MelissaWald ja schon angemerkt hat sind Befragten "Mitte 20".

**Comment by NSCI16** [comment]
Glaubt ihr es wäre interessant gewesen wenn wir noch das Geschlecht ausgewertet hätten ? Vllt. würde die geschlechtsspezifische Betrachtung mit der Interesse an naturwissenschaftlichen Fächern korrelieren.

**Comment by NSCI16** [comment]
Was wären sonst noch wichtige Eigenschaften die euerer Meinung nach nicht beachtet worden sind ?

**Comment by NSCI16** [comment]
Glaubt ihr es wäre interessant gewesen wenn wir noch das Geschlecht ausgewertet hätten ? Vllt. würde die geschlechtsspezifische Betrachtung mit der Interesse an naturwissenschaftlichen Fächern korrelieren.
Was wären sonst noch wichtige Eigenschaften die euerer Meinung nach nicht beachtet worden sind ?

**Comment by MelissaWald** [comment]
Ich denke, dass das Geschlecht auch interessant gewesen wäre. Man hätte noch den Zusammenhang von Mathe Interesse und Mathe LK anschauen können. Die Vermutung wäre da ja, dass Studierende mit hohem Interesse an Mathe auch den Mathe LK belegt haben.
Aber wir haben ja herausfinden können, dass die meisten Studierenden den Mathe LK belegt hatten.

**Comment by Josy-git** [comment]
Also wir hatten uns beim Programmieren  gedacht, dass wir die Wahrscheinlichkeit Interesse an Mathe oder Informatik vom Studiengang abhängig machen. Bei Mathe LK dachten wir uns, alle, die Mathe studieren oder Interesse an Mathe=7 haben, hatten Mathe LK.

**Comment by NSCI16** [comment]
Guter Einwand. @MelissaWald 
Außerdem hätte man untersuchen können ob der Mathe LK auch dazu geführt hat einen einfacheren Einstieg in das Studium zu finden oder nicht. Nur weil man kein Mathe LK hatte, heißt es nicht dass das Studium schwer fallen muss. Genauso andersrum.

**Comment by Timon-Ludwigs** [comment]
@NSCI16 
Das wäre mit den Daten aber nicht möglich gewesen. Dafür bräuchte man Noten oder andere Kategorien an denen man die Personen vergleichen kann. Oder übersehe ich etwas?

**Comment by Josy-git** [comment]
genau @NSCI16 !
Ich finde aber, die eigentlich Aufgabe war ja GitHub zu nutzen und das haben wir getan ;-)

Ich finde nämlich auch manche zusammenhänge inhaltlich weniger sinnvoll, aber wir konnten ja nur damit arbeiten, was wir hatten.

**Comment by NSCI16** [comment]
@Timon-Ludwigs das stimmt. 
Ich habe nur zusätzliche Messungsdaten vorgeschlagen, die noch weitere interessante Informationen geliefert hätten.

**Comment by Timon-Ludwigs** [comment]
@NSCI16 achso dann hatte ich das falsch verstanden. Aber ich stimme zu, dass das tatsächlich interessant wäre herauszufinden.

**Comment by joshuathejas** [comment]
@Josy-git ahhhh cool! 👍 Ich habe das mir auch mit diesem MatheLK gedacht, dass es einen Zusammenhang mit Fach und Interesse an Mathe gibt! :)

**Comment by Timon-Ludwigs** [comment]
Schön das ihr den Zusammenhang herausgefunden habt, den wir uns gedacht haben. 
Damit beende ich dann die Diskussion und bedanke mich bei allen für die tolle Zusammenarbeit.
