### ISSUE TITLE
Zusammenhang

### ISSUE THREAD

**Issue by Josy-git** [Timon-Ludwigs/Gruppenarbeit-Wissenschtliches-Arbeiten#3]
Wir sollten den Zusammenhang von Interesse und MatheLK wie besprochen einfügen.
Pushst du das?

**Comment by Timon-Ludwigs** [comment]
Ja, ich denke so machen wir es für die anderen besser zum Arbeiten. Genau ich pushe das.

**Comment by Josy-git** [comment]
Perfekt. Dann ändere auch die csv Datei. Dann haben wir Aufgabenteil 1 und 2 erledigt und es kann weitergehen. :-)
