### ISSUE TITLE
Funktionen Skript 1 und 2

### ISSUE THREAD

**Issue by Josy-git** [Timon-Ludwigs/Gruppenarbeit-Wissenschtliches-Arbeiten#4]
Welche Funktionen haltet ihr für sinnvoll?
Das könnten wir hier kurz besprechen.

**Comment by MelissaWald** [comment]
Für a könnten wir eine Funktion schreiben, die Minimum, Maximum, arithmetisches Mittel und Median ausgibt.

**Comment by Josy-git** [comment]
Vielleicht noch das 0.25 und 0.75-Quantil!

**Comment by Josy-git** [comment]
also für a haben wir ja genug.

b) da würde mir der Modalwert einfallen und vielleicht einfach die rel. und abs. Häufigkeiten?

**Comment by Josy-git** [comment]
bei c) vielleicht Cramer V oder Kontingenz C für zwei nominale Variablen,
 für ordinal und metrisch fällt mir grade nichts ein und
für zwei ordinale Spearmans Rangkorrelationskoeffizient?

**Comment by Josy-git** [comment]
bei d) punktbiserale Rangkorrelation

**Comment by Josy-git** [comment]
spannweite und interquartilsabstände noch bei ordinalen daten als despriktive statistiken

**Comment by MelissaWald** [comment]
Die Ideen hören sich schon sehr gut an. Ich probiere davon mal ein bisschen was aus, dann kann ich besser beurteilen wie gut das alles passt. Grade fallen mir dazu auch nicht mehr ein, aber ich schaue nochmal ob ich zu den jeweiligen Funktionen noch mehr finde. Für Skript 2 könnte man noch das arithmetische Mittel als Hilfsfunktion programmieren.

**Comment by joshuathejas** [comment]
Genau. Bei b. habe ich ein Frequency table und ein Proportions table erstellt. Bei a. würde ich auch modus reinmachen und ich habe für modus eine hilfsfunktion erstellt, weil es halt keine R Funktion for modus gibt.

**Comment by joshuathejas** [comment]
Bei c. habe ich erstmal nur die Kontingenztafel und chi-quadrat test für kategorialen Variablen berechnet.
Falls ihr andere Ideen habt, gerne Bescheid geben! :)

**Comment by NSCI16** [comment]
Ich habe ich mir @Josy-git deinen vorschlag für die d genauer angesehen. Man könnte aber auch eine Kontingenztafel nutzen. Außerdem gibt es eine nutzbereite Funktion in R die genau die punktbiserale Rangkorrelation berechnet.

**Comment by Josy-git** [comment]
Okay, dann schließen wir hier trotzdem noch nicht, falls wir uns doch noch umentscheiden.

**Comment by Josy-git** [comment]
Bei d haben wir jetzt etwas überlegt und eingefügt. Dann können wir hier schließen und die Auswertung kann weitergehen!
