### ISSUE TITLE
Funktion a

### ISSUE THREAD

**Issue by MelissaWald** [Timon-Ludwigs/Gruppenarbeit-Wissenschtliches-Arbeiten#5]
Ich hab für a jetzt folgende Funktion:
```
a <- function(X){  #X ist ein Vektor an Variablen aus dem Datensatz
min <- min(X)      #berechnet Minimum von X
max <- max(X)      #berechnet Maximum von X
ari <- mean(X)     #berechnet das arithmetische Mittel von X
var <- var(X)      #berechnet die Varians von X
med <- median(X)   #berechnet den Median von X
ra <- range(X)     #berechnet Spannweite von X
sd <- sd(X)        #berechnet Standardabweichnung von X
return(data.frame("Minimum"=min,"Maximum"=max,"Mittelwert"=ari,"Median"=med,"Varianz"=var, "Standardabweichung"=sd)) #erstellt Dataframe mit berechneten Werten und gibt diesen aus
}
```
 Man muss also hier den entsprechenden Vektor an Variablen bei a angeben und kann nicht einfach a(datensatz) machen. Hättet ihr das ähnlich gemacht oder gibt es da nen besseren Weg?
Gibt es ansonsten noch etwas, was ihr hinzufügen wollt?

**Comment by Josy-git** [comment]
kann man per a(datensatz$Alter) zb direkt auf eine Variable zugreifen?

**Comment by Timon-Ludwigs** [comment]
ja

**Comment by Josy-git** [comment]
Dann ist das zum auswerten doch top! Ich probiere es gleich mal aus!

**Comment by MelissaWald** [comment]
Ich füge das mal Skript 1 hinzu und wir können ja über nen Pull Request nochmal dann änderungen vornehmen.
